version: 2

project_name: mcd-cn

builds:
  - id: mcd-cn
    main: ./cmd/mcd-cn
    binary: mcd-cn
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
    ldflags:
      - -s -w -X github.com/ryanchen01/mcd-cn/internal/cli.Version={{.Version}}

archives:
  - id: mcd-cn
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: mcd-cn
    directory: Formula
    description: "CLI client for the McDonald's China MCP server."
    homepage: "https://github.com/ryanchen01/mcd-cn"
    license: "MIT"
    repository:
      owner: ryanchen01
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    install: |
      bin.install "mcd-cn"
    test: |
      system "#{bin}/mcd-cn", "version"
